### ISSUE TITLE
Error when loading html_chromium.dll (The procedure entry point cef_log could not be located)

### ISSUE THREAD

**Issue by EclipseLord** [Facepunch/gmod-html#1]
Hello, currently I'm experiencing a strange sort of error. The error I'm receiving is

> The procedure entry point cef_log could not be located in the dynamic link library *path to html_chromium.dll*

here's the code I'm currently using:
`HMODULE m_HChromium = LoadLibrary("path/to/html_chromium.dll");`

I have libcef in the same directory as html_chromium and same with chrome_elf and all the other dlls as well. I'm also using the x86 builds of libcef, html_chromium, and all the other dlls.
(im also implementing this into sourcesdk)
Is there anything else I'm missing or forgetting to add?

**Comment by willox** [comment]
Could the app be trying to load a `libcef.dll` library from somewhere else on your system like system32 or syswow64?

**Comment by EclipseLord** [comment]
I managed to use AddDllDirectory (I used SetDllDirectory because for whatever reason AddDllDirectory doesn't exist in windows.h, but it worked nevertheless) and disabled sandboxing (I think). But the error still persists. I also noticed trying to get and exported function via GetProcAddress on libcef always returned a nullptr.

**Comment by willox** [comment]
I can see that the libcef.dll files we ship to export a cef_log function. Maybe you can attach a debugger when your error message appears and look at the processes' loaded modules to see if libcef.dll has actually been loaded.

**Comment by EclipseLord** [comment]
apparently libcef.dll also existed in sourcesdk base 2013 sp. I fixed it by making my game "standalone" (its technically not standalone, I'm not to entirely sure on how you'd actually do that) and put the libcef and html_chromium.dll there. Thank you for your time and help.
